version: '3.8'

services:
  db:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  medusa:
    build: .
    container_name: ${CONTAINER_NAME}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: medusa develop

volumes:
  db_data:
